### ISSUE TITLE
SIGSEGV when upgrading with old data directory

### ISSUE THREAD

**Issue by jun0tpyrc** [OffchainLabs/arbitrum#1537]
built from git commit 
```
arb-node:a35de091f0029d05b42b1140e65cafd4f0bcbbde
=> 
arb-node:f565e0571b6883bd7021f926ba823e9d0b609b5f
```

occur on 1 testnet + 2 mainnet node

hopefully upgrade can be seamless without resync from block0 effort , so when chain history becomes large in data size, it's easier for hosting 

**(pruning the whole directory , seems block moving, so just an suggestion )**

```
{"level":"info","component":"configuration","l1url":"http://XXXXXXXlocal:8545","chainid":"1","time":"2021-08-27T07:05:31Z","caller":"/home/user/arb-util/configuration/configuration.go:350","message":"connected to l1 chain"}
{"level":"info","component":"arb-node","chainaddress":"c12ba48c781f6e392b49db2e25cd0c28cd77531a","chainid":"a4b1","type":"forwarder","time":"2021-08-27T07:05:31Z","caller":"/home/user/arb-rpc-node/cmd/arb-node/arb-node.go:175","message":"Launching arbitrum node"}
Reloading latest checkpoint
{"level":"info","component":"broadcaster","url":"wss://arb1.arbitrum.io/feed","time":"2021-08-27T07:06:14Z","caller":"/home/user/arb-util/broadcastclient/broadcastclient.go:117","message":"connecting to arbitrum inbox message broadcaster"}
{"level":"info","component":"arb-node","forwardTxURL":"https://arb1.arbitrum.io/rpc","time":"2021-08-27T07:06:14Z","caller":"/home/user/arb-rpc-node/cmd/arb-node/arb-node.go:235","message":"Arbitrum node starting in forwarder mode"}
{"level":"info","component":"txdb","start":"453317","count":2,"time":"2021-08-27T07:06:15Z","caller":"/home/user/arb-rpc-node/txdb/txdb.go:166","message":"adding logs"}
{"level":"info","component":"rpc","port":"8548","time":"2021-08-27T07:06:15Z","caller":"/home/user/arb-rpc-node/utils/rpc.go:61","message":"Launching websocket server over http"}
{"level":"info","component":"rpc","port":"8547","time":"2021-08-27T07:06:15Z","caller":"/home/user/arb-rpc-node/utils/rpc.go:61","message":"Launching rpc server over http"}
{"level":"info","component":"broadcaster","time":"2021-08-27T07:06:15Z","caller":"/home/user/arb-util/broadcastclient/broadcastclient.go:132","message":"Connected"}
{"level":"warn","component":"monitor","count":16,"time":"2021-08-27T07:06:15Z","caller":"/home/user/arb-node-core/monitor/inboxReader.go:361","message":"dropping outdated broadcast feed items after after feed caught up"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xda1db7]

goroutine 39 [running]:
github.com/offchainlabs/arbitrum/packages/arb-rpc-node/txdb.(*TxDB).GetBlock(0xc000516700, 0x36e9f, 0x1, 0x0, 0x0)
        /home/user/arb-rpc-node/txdb/txdb.go:475 +0xd7
github.com/offchainlabs/arbitrum/packages/arb-rpc-node/txdb.(*TxDB).handleBlockReceipt(0xc000516700, 0xc000074300, 0x10d0220, 0xc000074300)
        /home/user/arb-rpc-node/txdb/txdb.go:322 +0x1734
github.com/offchainlabs/arbitrum/packages/arb-rpc-node/txdb.(*TxDB).HandleLog(0xc000516700, 0x6eac5, 0x13330e0, 0xc000176240, 0xc00051e480, 0xc00051e480)
        /home/user/arb-rpc-node/txdb/txdb.go:256 +0x8f
github.com/offchainlabs/arbitrum/packages/arb-rpc-node/txdb.(*TxDB).AddLogs(0xc000516700, 0xc0007ac320, 0xc0007ac340, 0x2, 0x2, 0x0, 0x1a79080)
        /home/user/arb-rpc-node/txdb/txdb.go:169 +0x165
github.com/offchainlabs/arbitrum/packages/arb-util/core.(*LogReader).getLogs(0xc000563b80, 0x1332da0, 0xc000075340, 0x515656, 0x1230520)
        /home/user/arb-util/core/logreader.go:126 +0x5d3
github.com/offchainlabs/arbitrum/packages/arb-util/core.(*LogReader).Start.func1(0xc00051ea20, 0xc000563b80, 0x1332da0, 0xc000075340)
        /home/user/arb-util/core/logreader.go:43 +0x6b
created by github.com/offchainlabs/arbitrum/packages/arb-util/core.(*LogReader).Start
        /home/user/arb-util/core/logreader.go:41 +0xa6
```

**Comment by joshuacolvin0** [comment]
Old databases from pre-1.1.0 builds are not supported.
