### ISSUE TITLE
Should stop compilation if solc fails

### ISSUE THREAD

**Issue by ughe** [OffchainLabs/arbitrum#16]
The Arbitrum compiler should not be run if there is a solidity compiler error.

## Steps to reproduce:

```
git clone --depth=1 https://github.com/OffchainLabs/demo-dapp-pet-shop ps && cd ps
yarn
truffle migrate --reset --all --network arbitrum
echo INVALID >> contracts/Adoption.sol
truffle migrate --reset --all --network arbitrum
```

## Observed error:

```
$ truffle migrate --reset --all --network arbitrum

Compiling your contracts...
===========================
Error: Error: CompileError: ParsedContract.sol:36:2: ParserError: Expected pragma, import directive or contract/interface/library definition.
}INVALID
 ^-----^

Compilation failed. See above.
    at Object.compile (~/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-workflow-compile/index.js:103:1)
Truffle v5.0.22 (core: 5.0.22)
Node v10.16.0
arbc-truffle-compile compiled.json contract.ao
Adoption 784030224795475933405737832577560929931042096197
Migrations 536549294809709735284832398280003200128834709884
6902
```

## Expected behavior:

`arbc-truffle-compile` should not run if the truffle compilation fails

Note: the very first time an invalid migrate is run (or whenever the `build/` folder does not exist) then the behavior is correct because `arbc-truffle-compile` is not run:

```
Compiling your contracts...
===========================
Error: Error: CompileError: ParsedContract.sol:36:2: ParserError: Expected pragma, import directive or contract/interface/library definition.
}INVALID
 ^-----^

Compilation failed. See above.
    at Object.compile (~/.npm-global/lib/node_modules/truffle/build/webpack:/packages/truffle-workflow-compile/index.js:103:1)
Truffle v5.0.22 (core: 5.0.22)
Node v10.16.0
Error: ENOENT: no such file or directory, scandir 'build/contracts'
    at Object.readdirSync (fs.js:790:3)
    at process.on (~/ps/node_modules/arb-truffle-provider/lib/index.js:36:20)
    at process.emit (events.js:203:15)
    at process.emit (~/.npm-global/lib/node_modules/truffle/build/webpack:/~/source-map-support/source-map-support.js:465:1)
```

**Comment by hkalodner** [comment]
This is no long relevant since we've removed arb-provider-truffle
