### ISSUE TITLE
arb-deploy handle invalid contract.ao

### ISSUE THREAD

**Issue by ughe** [OffchainLabs/arbitrum#17]
## Steps to reproduce in dev-mode:

```
git clone htttps://github.com/OffchainLabs/demo-dapp-pet-shop pet-shop
cd pet-shop
arb-deploy --dev-mode contract.ao 3
```

## Expected error:

```
arb-validator-coordinator_1  | Finished waiting for arb-ethbridge:7545...
arb-validator-coordinator_1  | cp: omitting directory 'contract.ao'
arb-validator-coordinator_1  | incorrect version of .ao file
arb-validator-coordinator_1  | expected version 1 found version 0
arb-validator-coordinator_1  | 2019/08/01 14:57:30 open private_key.txt: no such file or directory
pet-shop_arb-validator-coordinator_1 exited with code 1
```

## Secondary error:

Trying to fix this by creating a `contract.ao` by running:

```
truffle migrate --reset --network arbitrum
```

Will then lead to the secondary error:

```
...
arbc-truffle-compile compiled.json contract.ao
...
Traceback (most recent call last):
  File "/usr/local/bin/arbc-truffle-compile", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File ".../arbc-solidity/bin/arbc-truffle-compile", line 33, in <module>
    with open(args.output_file, "wb") as f:
IsADirectoryError: [Errno 21] Is a directory: './contract.ao'
```

This is because arb-deploy attempts to mount `contract.ao` as a volume. Because it does not exist, an empty directory is created named `contract.ao`. This is then a problem for arbc-truffle-compile.

## Proposed solution

Check that `contract.ao` is a valid file before using it in `arb-deploy`

**Comment by hkalodner** [comment]
This is no longer relevant since arb-deploy uses arbos rather than letting you specify a contract file
