### ISSUE TITLE
Failure: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.5.0)

### ISSUE THREAD

**Issue by choisol0729** [OffchainLabs/arbitrum#1899]
Hello!

I am arb-ts user who are trying to figure out why the error on the title is occurring whenever I try to deposit my ERC20 contract on the arbitrum network. I know this package is using ethers as well, and I thought the problem was in ethers' side, but at this point, I have no idea on which side is an error :(

`
Providers getting ready for deposit custom token...
Layer 1 provider has been readied...
Layer 2 provider has been readied...
Providers have been established... Waiting for Bridge initiation
Token Amount: 100000000000000000000
Bridge Has been initiated!
Target Token Address: 0x44fDeA76EC6fec17Ef5d6230dd232a0766DD6238
Transaction Hash: 0x3982b79f746cba1d9fbb55bde849d30a48518dedf0a712d4c75bb33315507f6c
Completed Approving Contract. You will be seeing the result very soon
Type of data type Contract Address: string

offline: Failure: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.5.0)
Error: invalid address or ENS name (argument="name", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.5.0)
    at Logger.makeError (/Users/solchoi/Desktop/TrufflePicple/node_modules/@ethersproject/logger/lib/index.js:199:21)
    at Logger.throwError (/Users/solchoi/Desktop/TrufflePicple/node_modules/@ethersproject/logger/lib/index.js:208:20)
    at Logger.throwArgumentError (/Users/solchoi/Desktop/TrufflePicple/node_modules/@ethersproject/logger/lib/index.js:211:21)
    at /Users/solchoi/Desktop/TrufflePicple/node_modules/@ethersproject/contracts/lib/index.js:93:32
    at step (/Users/solchoi/Desktop/TrufflePicple/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/solchoi/Desktop/TrufflePicple/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/solchoi/Desktop/TrufflePicple/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
`

Above is the result (+ some debug that I put in), but most of the codes are from the integration test / tutorial codes from github :(

The approving contract part seems to be fine, but whenever it gets to deposit, It does not go that well...
Currently, I am guessing that it has to do something with the abi / bytecode in L1gatewayrouter, but that's just a guess of mine, and I have no idea what is going on to be honest. 

Excuse me if there's a certain format to make sure that I broke in this post, this is my second time issuing anything on github. (The first one was on ethers package)

If anyone has any idea, feel free to comment or question, I will try to provide additional info ASAP. Cheers

**Comment by joshuacolvin0** [comment]
Please ask in discord support channel, thank you
https://discord.gg/arbitrum
