### ISSUE TITLE
CALL_EXCEPTION error when trying to call bridge.depositETH

### ISSUE THREAD

**Issue by davidhetiktok** [OffchainLabs/arbitrum#2157]
I am trying to use arb-ts for depositing eth L1 -> L2, and hitting this error. Can anyone help?

        const amountRaw = utils.parseUnits(amount, 18);
        const tx = await bridge.depositETH(amountRaw);
        const receipt = await tx.wait();

Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="getSubmissionPrice(uint256)", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.6.0)
    at Logger.makeError (index.js:219:1)
    at Logger.throwError (index.js:228:1)
    at Interface.decodeFunctionResult (interface.js:339:1)
    at Object.<anonymous> (index.js:293:1)
    at Generator.next (<anonymous>)
    at fulfilled (index.js:5:43)

**Comment by davidhetiktok** [comment]
testing on Rinkeby

**Comment by davidhetiktok** [comment]
nvm.... stupid mistake on my end. Was able to troubleshoot it. Sorry for trouble!
