### ISSUE TITLE
Validators panic if connection to block chain lost

### ISSUE THREAD

**Issue by ughe** [OffchainLabs/arbitrum#4]
## Steps to re-produce:

1. Start a demo dapp i.e. `arb-deploy --dev-mode --keep-alive contract.ao 3`
2. `docker ps`
3. `docker kill pet-shop_arb-ethbridge_1`

## Expected error (excerpt):

```
arb-validator1_1             | panic: runtime error: invalid memory address or nil pointer dereference
arb-validator1_1             | [signal SIGSEGV: segmentation violation code=0x1 addr=0x1c0 pc=0x56279644cbba]
arb-validator1_1             | 
arb-validator1_1             | goroutine 94 [running]:
arb-validator1_1             | github.com/offchainlabs/arb-validator/validator.(*Validator).Run.func1(0xc0000c0000, 0xc0000af5c0, 0x5627968d39a0, 0xc0000200b0)
arb-validator1_1             | 	/home/user/validator/validator.go:188 +0x26a
arb-validator1_1             | created by github.com/offchainlabs/arb-validator/validator.(*Validator).Run
arb-validator1_1             | 	/home/user/validator/validator.go:176 +0x5f
arb-validator-coordinator_1  | panic: dial tcp: lookup arb-ethbridge on 127.0.0.11:53: no such host
arb-validator-coordinator_1  | 
arb-validator-coordinator_1  | goroutine 64 [running]:
arb-validator-coordinator_1  | github.com/offchainlabs/arb-validator/ethvalidator.(*EthValidator).StartListening.func1(0xc0000ae028, 0xc0000200b0, 0xc000532f60, 0xc0000ae038)
arb-validator-coordinator_1  | 	/home/user/ethvalidator/validator.go:185 +0x51d
arb-validator-coordinator_1  | created by github.com/offchainlabs/arb-validator/ethvalidator.(*EthValidator).StartListening
arb-validator-coordinator_1  | 	/home/user/ethvalidator/validator.go:162 +0x156
```

**Comment by hkalodner** [comment]
Validators now print "Error: Validator can't connect to blockchain" on disconnect and periodically try to reconnect every 5 seconds.
